name: socketful
version: 0.0.3
author: Alexander Adeniyin Ewetumo <trinoxf@gmail.com>
description:   extendable socket(websocket,tcpsocket) api for both client and server
homepage: http://influx.github.com/socketful.git
dependencies:
  streamable: any
  hub: any
  dispatch: any
  browser: any
